# Tutorial - Basic
---
This tutorial demonstrates the basic use of qton.

## To create a quantum circuit object

To create a quantum circuit, using the class 'Circuit'.

In [1]:
from qton import Circuit

num_qubits = 2
circ = Circuit(num_qubits)

'circ' now is a circuit with 2 qubits. Its state vector can be invoked as below.

In [2]:
circ.state

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

By default, the circuit state is initialized to the state corresponds to all qubits in $Z$ up mode.

## To create a Bell state

A Bell state usually means  
$$ \frac{|00\rangle + |11\rangle}{\sqrt 2} .$$

In [3]:
circ.h(0)
circ.cx(0, 1)

We act a Hadamard gate on qubit 0 followed by a CNOT gate on both qubit 0 and 1. In our convention, qubits are indexed by integers.

Show the current state,

In [4]:
circ.state

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

Which is just the **Bell state** we metioned above.

## To measure a circuit

To measure a circuit, using the method 'measure'

In [5]:
circ.measure()

3

This method returns a basis index. For example, '2' means it returns a result on basis $|10\rangle$.

The 'measure' method doesn't damage the circuit state like the real one does.  So you can repeat it to increase the statistics.

## Statistics on the Bell state

In [6]:
result = [0, 0, 0, 0]
N = 100  # Times of the measurements.
for i in range(N):
    basis = circ.measure()
    result[basis] += 1

Check the results below.

In [7]:
result

[51, 0, 0, 49]

## To initialize a circuit

Since the state vector is just a numpy array,  you can initialize it like any numpy vector.  'Circuit' class also include a 'initialize' method.

In [8]:
circ.initialize([0, 0, 0, 1])

In [9]:
circ.state

array([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j])

Note the vector you use to initialize a circuit must be normalized in advance.  And its length must be consistent with the qubit number.

## A list for gate methods

All gate prototypes can be found in module 'gate.py'.

**single qubit gate**  
Assuming all of them act on the 0th qubit of an object 'circ'.  

circ.h(0)  # Hadamard gate  
circ.x(0)  # Pauli X gate  
circ.y(0)  # Pauli Y gate  
circ.z(0)  # Pauli Z gate  
circ.s(0)  # Phase gate  
circ.t(0)  # pi/8 gate  

These have an extra custom parameter in, which we set it to 'pi'.  
circ.rx(pi, 0)  # Rotation along X axis  
circ.ry(pi, 0)  # Rotation along Y axis  
circ.rz(pi, 0)  # Rotation along Z axis  

**double qubit gate**  
For all controlled gates, assuming qubit 0 is control, qubit 1 is target.

circ.ch(0, 1)  # Controlled Hadamard gate  
circ.cx(0, 1)  # Controlled X gate, also known as Controlled Not gate  
circ.cy(0, 1)  # Controlled Y gate  
circ.cz(0, 1)  # Controlled Z gate  
circ.sw(0, 1)  # Swap gate  

'pi' is still an example for the custom parameter.  
circ.crx(pi, 0, 1)  # Controlled rotation along X axis  
circ.cry(pi, 0, 1)  # Controlled rotation along Y axis  
circ.crz(pi, 0, 1)  # Controlled rotation along Z axis  