# Tutorial - Characterization of A Quantum Function
---
Sometimes we may be interested in a balck box function. A complete characterization of it is to write down its corresponding representation. In this tutorial we demonstrate how to do this to a quantum function.

In [1]:
import numpy as np
from qton import Circuit

## Definition of function
We create a black box function, which can be used to prepare a so-called GHZ state. 

In [8]:
def black_box_function(obj):
    '''
    This function can prepare a Bell or GHZ state.
    'obj' should be a Circuit object.
    '''
    num_qubits = obj.number_of_qubits
    obj.h(0)
    for i in range(1, num_qubits):
        obj.cx(0, i)
    return

Let's check its effect.

In [3]:
n = 2  # Number of qubits.
circ = Circuit(n)
black_box_function(circ)

circ.state

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

## Representation of the function
The balck box function has a unitary matrix representation. Our aim is to find it out. Suppose $U_f$ is this function, its matrix elements are $\langle z_i|U_f|z_j \rangle$. Here $|z_i\rangle$ is the $i$th basis of the circuit.

In [4]:
matrix = np.zeros((2**n, 2**n), complex)  # Matrix representation of the black box function.
for i in range(2**n):
    bra = np.zeros(2**n)
    bra[i] = 1.
    for j in range(2**n):
        ket = np.zeros(2**n)
        ket[j] = 1.
        circ.initialize(ket)  # Reset circuit's state with 'ket'.
        black_box_function(circ)
        matrix[i, j] = np.dot(np.conj(bra), circ.state)

Display the matrix representation,

In [5]:
matrix.real

array([[ 0.70710678,  0.        ,  0.70710678,  0.        ],
       [ 0.        ,  0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  0.70710678,  0.        , -0.70710678],
       [ 0.70710678,  0.        , -0.70710678,  0.        ]])

In [6]:
matrix.imag

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Let's check if this matrix can produce a GHZ state.

In [7]:
ket = np.zeros(2**n)
ket[0] = 1.

np.matmul(matrix, ket)

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

This is same as above, which backs our assert up.